VERSION 0.8

BUILD:
    FUNCTION

    DO +CONTAINER

    # Copy the configuration files into the container
    COPY tsconfig.json .

    # Build the action
    RUN npm run-script package

    # Save the build artifacts
    SAVE ARTIFACT dist AS LOCAL dist
    SAVE ARTIFACT node_modules AS LOCAL node_modules

CONTAINER:
    FUNCTION

    FROM node:22-alpine
    WORKDIR /earthly-actions-setup

    # Copy the package.json into the container
    COPY package.json package-lock.json .

    # Install dependencies
    RUN npm ci

    # Copy the source code into the container
    COPY --dir src .

DIFF_ARTIFACT:
    FUNCTION

    # Compile and copy the latest source code
    DO +BUILD

    # Copy the version that has been committed to the repository
    COPY dist /from-git

    # Diff the two versions
    RUN diff -r /from-git dist >/dev/null || (echo "dist and +compile/dist are different, did you forget to run earthly +compile?" && exit 1)

LINT:
    FUNCTION

    DO +CONTAINER

    # Copy the configuration files into the container
    COPY eslint.config.cjs .

    # Run the linting command
    RUN npm run-script lint

TEST:
    FUNCTION

    DO +CONTAINER

    # Copy the configuration files into the container
    COPY tsconfig.json .
    COPY vitest.config.ts .

    # Run the test command
    RUN npm test

TEST_ACTION:
    FUNCTION

    DO +CONTAINER

    # Copy the compiled action into the container
    COPY --dir dist .

    # Set the cache directory
    ENV RUNNER_TOOL_CACHE=/tmp/cache-dir

    # Run the action and capture the output
    RUN node dist/setup/index.js | tee output

    # Validate that the cache was not populated yet
    RUN ! grep 'Found tool in cache' output

    # Extract the earthly path from the output
    RUN cat output | grep '^::add-path::' | sed 's/::add-path:://g' > earthly-path
    RUN test "$(cat earthly-path)" = "/root/.earthly/bin"

    # Validate the earthly version
    RUN export PATH="$(cat earthly-path):$PATH" && earthly --version | tee version.output
    RUN grep '^earthly version v*' version.output

    # Validate cache was populated by the prior run
    RUN node dist/setup/index.js | tee output2
    RUN grep 'Found tool in cache' output2
