---
name: "Action"

"on":
  pull_request:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  latest:
    name: Install the latest version
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm ci

      - name: Package the action
        run: npm run package

      - name: Run the action to install the latest version
        uses: ./

      - name: Verify that earthly is installed
        run: earthly --version

  specific:
    name: Install a specific version
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        # windows was not available < v0.5.15
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm ci

      - name: Package the action
        run: npm run package

      - name: Run the action and install a specific version
        uses: ./
        with:
          version: 0.5.15

      - name: Verify that earthly is installed
        run: earthly --version

  patch-range:
    name: Install a patch range version
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm ci

      - name: Package the action
        run: npm run package

      - name: Run the action and install a patch range version
        uses: ./
        with:
          version: 0.6.*

      - name: Verify that earthly is installed
        run: earthly --version

  major-range:
    name: Install a major range version
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm ci

      - name: Package the action
        run: npm run package

      - name: Run the action and install a major range version
        uses: ./
        with:
          version: ^0.6.1

      - name: Verify that earthly is installed
        run: earthly --version
